"""Tenant profiles: three deployments that genuinely differ, and a browser payload that leaks
nothing.

The claim the demo makes is "same engine, three books of business". These tests are what keeps
that from becoming a skin: distinct corpora, substantively different tuning, and a routing map
that is display-only so the model's decision contract stays closed.
"""

from __future__ import annotations

import pytest

from earshot.agent.schemas import OwningTeam
from earshot.tenants import CANONICAL_TEAMS, TENANTS, Tenant, resolve, tenant

# The canonical routing slots, taken from the decision contract itself rather than retyped. If
# `OwningTeam` gains a value, this test tells the tenant profiles about it.
CONTRACT_TEAMS = set(OwningTeam.__args__) - {"none"}


def test_there_are_at_least_three_deployments() -> None:
    assert len(TENANTS) >= 3


def test_every_tenant_has_its_own_corpus() -> None:
    """Distinct seeds, so no two tenants are the same customers under two brands.

    A shared seed would make the multi-enterprise screen a presentation trick: the same 44 people
    with three logos over them. The config hash differing is the stronger statement, because it
    covers the tuning as well.
    """
    seeds = [t.run.seed for t in TENANTS]
    hashes = [t.run.hash() for t in TENANTS]
    assert len(set(seeds)) == len(seeds), f"tenants share a seed: {seeds}"
    assert len(set(hashes)) == len(hashes), f"tenants share a config hash: {hashes}"


def test_tuning_differs_substantively_not_just_cosmetically() -> None:
    """Half-lives and thresholds must actually differ, or the deployments are a skin.

    A card issuer's complaint decays in weeks and a mortgage servicer's hardship signal does not;
    if every tenant scored identically, a judge would be right to call the multi-enterprise claim
    decoration.
    """
    half_lives = {
        t.tenant_id: tuple(sorted(t.run.scoring.half_life_days.items())) for t in TENANTS
    }
    assert len(set(half_lives.values())) > 1, "every tenant decays identically"
    thresholds = {t.threshold for t in TENANTS}
    assert len(thresholds) > 1, "every tenant alerts at the same cut"


@pytest.mark.parametrize("t", TENANTS, ids=lambda t: t.tenant_id)
def test_team_map_covers_every_slot_in_the_decision_contract(t: Tenant) -> None:
    """A slot with no local name renders as the raw canonical string on a client screen."""
    assert set(t.teams) == CONTRACT_TEAMS == set(CANONICAL_TEAMS)


@pytest.mark.parametrize("t", TENANTS, ids=lambda t: t.tenant_id)
def test_team_names_are_unique_within_a_tenant(t: Tenant) -> None:
    assert len(set(t.teams.values())) == len(t.teams)


def test_team_label_falls_back_rather_than_raising() -> None:
    """`owning_team` can be `"none"`. A decision that routed nowhere must still render."""
    t = TENANTS[0]
    assert t.team_label("none") == "unrouted"
    assert t.team_label(None) == "unrouted"
    assert t.team_label("not_a_team") == "not_a_team"


@pytest.mark.parametrize("t", TENANTS, ids=lambda t: t.tenant_id)
def test_public_payload_withholds_the_seed(t: Tenant) -> None:
    """The seed is the one value a browser must never hold.

    From it, `stratum`, `outcome` and `latent_risk` can be regenerated by anyone with the repo --
    which is exactly the shortcut `tools/ui_fixture.py` exists to prevent. Corpus parameters are
    withheld for the same reason: enough of them, plus the seed, is the corpus.
    """
    public = t.public()
    blob = repr(public)
    assert "seed" not in public
    assert str(t.run.seed) not in blob
    assert public["synthetic"] is True


def test_resolve_all_returns_declaration_order() -> None:
    assert [t.tenant_id for t in resolve("all")] == [t.tenant_id for t in TENANTS]


def test_resolve_takes_a_list_in_the_order_given() -> None:
    got = resolve(f"{TENANTS[1].tenant_id},{TENANTS[0].tenant_id}")
    assert [t.tenant_id for t in got] == [TENANTS[1].tenant_id, TENANTS[0].tenant_id]


def test_unknown_tenant_names_the_known_ones() -> None:
    """A typo surfaces as the fix, not as a KeyError three frames later."""
    with pytest.raises(KeyError, match="known:"):
        tenant("nrothwind")
